### ISSUE TITLE
Particle Representation is not obtained from video directly

### ISSUE THREAD

**Issue by NagabhushanSN95** [YunzhuLi/VGPL#1]
Hi,
Please correct me if I'm wrong. From the code, I see that you're not extracting coarse particle positions from the visual prior module. Instead you're reading those values from pre-saved files in `perception` folder. Did you run visual prior offline and save these files? Can you please tell me how you obtained these files? i.e. how can I get initial particle position estimate using visual prior module?

**Comment by YunzhuLi** [comment]
Yes, we run the visual prior offline and save the results in the `perception` folder for training the inference module. We have edited the readme file, and you can check the newly added section for details of the perception module.
[https://github.com/YunzhuLi/VGPL#2-visual-prior](https://github.com/YunzhuLi/VGPL#2-visual-prior)

**Comment by NagabhushanSN95** [comment]
Cool. Thanks a lot
